### ISSUE TITLE
Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.

### ISSUE THREAD

**Issue by PeterStrick** [Mopsgamer/BetterDiscord-codes#28]
I am unable to use the Animations Plugin on Powercord.

Powercord Version: v2 (12de9dc)
Discord Canary Version: 114036 (143eee1)
bdCompat Version: 0.3.10
Animations Plugin Version: [1.2.7.3](https://github.com/Mopsgamer/BetterDiscord-codes/commit/58e9e4fdf3d00e513074f6960f59fc60028c270f)

Screenshot: 
![image](https://user-images.githubusercontent.com/60312421/153254499-97fa9a39-408c-4f6b-ba88-3761c733d2e2.png)

**Comment by Mopsgamer** [comment]
I do not support PowerCord.

The error itself is caused by not finding the element used in BetterDiscord - "bd-themes". With this I can fix problems related to compatibility with themes.
`this.observer.observe(document.getElementsByTagName("bd-themes")[0], {"childList": true})`

Try asking this question on the PowerCord server, maybe someone knows what is needed to fix this problem in your case.
